# Generated by Django 5.1.1 on 2024-09-30 16:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MovieRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Theatre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=500)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieName', models.CharField(max_length=225)),
                ('is_active', models.BooleanField(default=True)),
                ('trailer', models.URLField(blank=True)),
                ('rating', models.CharField(max_length=10)),
                ('mpaa_rating', models.CharField(max_length=10)),
                ('runtime', models.IntegerField()),
                ('year', models.IntegerField()),
                ('critics_score', models.IntegerField()),
                ('audience_score', models.IntegerField()),
                ('description', models.TextField(max_length=500)),
                ('thumbnail', models.URLField()),
                ('photo', models.URLField()),
                ('studio', models.CharField(max_length=100)),
                ('genres', models.ManyToManyField(blank=True, related_name='movies', to='CinemaApp.genre')),
            ],
        ),
        migrations.CreateModel(
            name='MovieProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='Member', max_length=100)),
                ('user', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movie_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShowTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showtimes', to='CinemaApp.movie')),
                ('movieRoom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showtimes', to='CinemaApp.movieroom')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seatID', models.CharField(max_length=5)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_available', models.BooleanField(default=True)),
                ('showTime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='CinemaApp.showtime')),
            ],
        ),
        migrations.AddField(
            model_name='movieroom',
            name='theatre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_rooms', to='CinemaApp.theatre'),
        ),
    ]
