# Generated by Django 5.1.1 on 2024-09-30 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CinemaApp', '0003_promotion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='mpaa_rating',
        ),
    ]
