# Generated by Django 5.1.1 on 2024-10-03 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CinemaApp', '0007_alter_address_user_alter_payment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieroom',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
