# Generated by Django 5.1.1 on 2024-10-07 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CinemaApp', '0009_movie_director_movieprofile_customer_state_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='director',
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('movies', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='director', to='CinemaApp.movie')),
            ],
        ),
    ]
