# Generated by Django 5.1.1 on 2024-10-07 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CinemaApp', '0011_alter_director_movies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='director',
            name='movies',
        ),
        migrations.AddField(
            model_name='director',
            name='movies',
            field=models.ManyToManyField(blank=True, null=True, related_name='director', to='CinemaApp.movie'),
        ),
    ]
