# Generated by Django 5.1.1 on 2024-10-15 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CinemaApp', '0013_order_promotion_showtime_date_alter_movie_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='movies',
            field=models.ManyToManyField(related_name='director', to='CinemaApp.movie'),
        ),
    ]
