# Generated by Django 5.1.1 on 2024-10-24 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CinemaApp', '0014_alter_director_movies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='CVV',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='cardNumber',
        ),
    ]
