# Generated by Django 5.1.1 on 2024-10-24 16:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CinemaApp', '0015_remove_payment_cvv_remove_payment_cardnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='CVV',
            field=models.BinaryField(default=0),
        ),
        migrations.AddField(
            model_name='payment',
            name='cardNumber',
            field=models.BinaryField(default=0),
        ),
        migrations.AlterField(
            model_name='payment',
            name='expirationDate',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='payment',
            name='firstName',
            field=models.CharField(default='Jon', max_length=40),
        ),
        migrations.AlterField(
            model_name='payment',
            name='lastName',
            field=models.CharField(default='Doe', max_length=40),
        ),
    ]
