# Generated by Django 5.1.1 on 2024-10-24 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CinemaApp', '0016_payment_cvv_payment_cardnumber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieprofile',
            name='receive_promotions',
            field=models.BooleanField(default=False),
        ),
    ]
