# Generated by Django 5.1.1 on 2024-10-24 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CinemaApp', '0017_movieprofile_receive_promotions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='discountRate',
            field=models.IntegerField(),
        ),
    ]
