# Generated by Django 5.1.1 on 2024-10-24 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CinemaApp', '0018_alter_promotion_discountrate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promotion',
            old_name='discountRate',
            new_name='discountPercentage',
        ),
    ]
