# Generated by Django 5.1.1 on 2024-11-07 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CinemaApp', '0021_alter_address_city_alter_address_postalcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='address',
            name='postalCode',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(max_length=150),
        ),
    ]
