# Generated by Django 5.1.1 on 2024-11-07 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CinemaApp', '0022_alter_address_city_alter_address_postalcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieroom',
            name='numOfRows',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='movieroom',
            name='seatPerRow',
            field=models.IntegerField(default=16),
        ),
    ]
