# Generated by Django 5.1.1 on 2024-11-07 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CinemaApp', '0023_movieroom_numofrows_movieroom_seatperrow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theatre',
            name='address',
        ),
    ]
