# Generated by Django 5.1.1 on 2024-11-07 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CinemaApp', '0024_remove_theatre_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='theatre',
            name='city',
            field=models.CharField(default='Athens', max_length=50),
        ),
        migrations.AddField(
            model_name='theatre',
            name='state',
            field=models.CharField(default='GA', max_length=50),
        ),
        migrations.AddField(
            model_name='theatre',
            name='street',
            field=models.CharField(default='1020 Milledge Ave', max_length=100),
        ),
        migrations.AddField(
            model_name='theatre',
            name='zipcode',
            field=models.CharField(default=30019, max_length=20),
        ),
    ]
