# Generated by Django 5.1.1 on 2024-11-07 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CinemaApp', '0025_theatre_city_theatre_state_theatre_street_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movieroom',
            old_name='seatPerRow',
            new_name='seatsPerRow',
        ),
    ]
