# Generated by Django 5.1.1 on 2024-11-11 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CinemaApp', '0027_alter_movieroom_seatsperrow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='promotion',
        ),
        migrations.AddField(
            model_name='order',
            name='discountPercentage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='totalPrice',
            field=models.FloatField(default=0),
        ),
    ]
