# Generated by Django 5.1.1 on 2024-11-18 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CinemaApp', '0028_remove_order_promotion_order_discountpercentage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adult_price', models.DecimalField(decimal_places=2, default=10.0, max_digits=6)),
                ('senior_price', models.DecimalField(decimal_places=2, default=8.0, max_digits=6)),
                ('child_price', models.DecimalField(decimal_places=2, default=6.0, max_digits=6)),
                ('booking_fee', models.DecimalField(decimal_places=2, default=2.0, max_digits=6)),
                ('last_updated', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
