# Generated by Django 5.1.1 on 2024-11-18 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CinemaApp', '0029_prices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='price',
        ),
    ]
