# Generated by Django 5.1.1 on 2024-12-06 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CinemaApp', '0032_remove_order_payment_order_card_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='card_number',
        ),
        migrations.AddField(
            model_name='order',
            name='cardNumber',
            field=models.BinaryField(default=0),
        ),
    ]
