# Generated by Django 5.1.1 on 2024-12-06 02:41

import CinemaApp.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CinemaApp', '0033_remove_order_card_number_order_cardnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='theatre',
            field=models.ForeignKey(default=CinemaApp.models.default_theatre, on_delete=django.db.models.deletion.CASCADE, related_name='movies_showing', to='CinemaApp.theatre'),
        ),
    ]
