# Generated by Django 5.1.1 on 2024-12-06 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CinemaApp', '0034_movie_theatre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cardNumber',
            field=models.IntegerField(default=0),
        ),
    ]
