# Generated by Django 5.1.1 on 2024-12-06 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CinemaApp', '0036_alter_order_cardnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='prices',
            name='sales_tax',
            field=models.FloatField(default=0.06),
        ),
    ]
