# Generated by Django 5.1.1 on 2024-12-06 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CinemaApp', '0037_prices_sales_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prices',
            name='adult_price',
            field=models.DecimalField(decimal_places=2, default=12.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='prices',
            name='booking_fee',
            field=models.DecimalField(decimal_places=2, default=2.99, max_digits=6),
        ),
        migrations.AlterField(
            model_name='prices',
            name='child_price',
            field=models.DecimalField(decimal_places=2, default=9.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='prices',
            name='senior_price',
            field=models.DecimalField(decimal_places=2, default=9.0, max_digits=6),
        ),
    ]
