# Generated by Django 5.1.1 on 2024-12-06 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CinemaApp', '0038_alter_prices_adult_price_alter_prices_booking_fee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prices',
            name='last_updated',
        ),
    ]
