# Generated by Django 5.1.1 on 2024-12-06 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CinemaApp', '0039_remove_prices_last_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='billing_address',
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(default='North Pole', max_length=150),
        ),
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(default='North Artica', max_length=40),
        ),
        migrations.AddField(
            model_name='order',
            name='street',
            field=models.CharField(default='123 Reindeer Ln', max_length=150),
        ),
        migrations.AddField(
            model_name='order',
            name='zip',
            field=models.CharField(default='12345', max_length=15),
        ),
    ]
