# Generated by Django 5.1.1 on 2024-12-09 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CinemaApp', '0041_order_is_refunded_alter_ticket_seat'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='movie_name_refunded',
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
    ]
