# Generated by Django 5.1.1 on 2024-12-09 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CinemaApp', '0042_order_movie_name_refunded'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='showStartTime',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
